# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sveltosctl < Formula
  desc "A CLI to nicely display resources/helm charts deployed in Cluster managed by Sveltos"
  homepage "https://github.com/projectsveltos/sveltosctl"
  version "0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhaykohli/sveltosctl-ak/releases/download/v0.2/sveltosctl_Darwin_x86_64.tar.gz"
      sha256 "9b94298637a2cabee94995465db9230d6a731370b4366ebe36db0bcf95a35f5a"

      def install
        bin.install "sveltosctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhaykohli/sveltosctl-ak/releases/download/v0.2/sveltosctl_Darwin_arm64.tar.gz"
      sha256 "18fd814bb5a0fa08f6787bc0e2a0e0d73a44478f9d36835331f6103be6532289"

      def install
        bin.install "sveltosctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhaykohli/sveltosctl-ak/releases/download/v0.2/sveltosctl_Linux_x86_64.tar.gz"
      sha256 "93f04e2bd89596d8063cf3a727879bcd2f97e47a1fe2cce7678db18f6fa1a66f"
      def install
        bin.install "sveltosctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhaykohli/sveltosctl-ak/releases/download/v0.2/sveltosctl_Linux_arm64.tar.gz"
      sha256 "c882cf420b66a0416fdae8442490f2f908420c0b99ab3ead2f91c9212273da20"
      def install
        bin.install "sveltosctl"
      end
    end
  end
end
